In [2]:
%pip install numpy

Collecting numpy
  Using cached numpy-2.4.6-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Using cached numpy-2.4.6-cp313-cp313-win_amd64.whl (12.3 MB)
Installing collected packages: numpy
Successfully installed numpy-2.4.6
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import numpy as np

In [5]:
print(np.__version__)

2.4.6

<b> Working on loading datasets from <br>
1. CSV File<br>
2. Excel File<br>
3. Parquet File

In [1]:
%pip install -q pandas openpyxl pyarrow

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd
import os

<b>Load the CSv file

In [2]:
df=pd.read_csv("titanic.csv")

In [3]:
print(type(df))

<class 'pandas.DataFrame'>

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 118.9 KB

<b>Load Selected Columns

In [7]:
#pd.read_csv?

In [16]:
df.shape

(891, 12)

In [14]:
df_csv_subset=pd.read_csv("titanic.csv",
                          usecols=["Survived","Pclass","Age","Fare"]
)

In [17]:
df_csv_subset.shape

(891, 4)

In [15]:
df_csv_subset.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

<b>For n rows

In [23]:
df_csv_preview=pd.read_csv("titanic.csv",nrows=10)

In [20]:
df_csv_preview.shape

(10, 12)

<b>Working with Excel File

In [24]:
df_excel=pd.read_excel("titanic.xlsx",nrows=20)

In [29]:
df_excel.shape

(20, 12)

In [27]:
df_excel_subset=pd.read_excel("titanic.xlsx",
                              usecols=["PassengerId","Age","Sex","Fare"])

In [30]:
df_excel_subset.shape

(891, 4)

In [31]:
df_excel_subset.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Sex          891 non-null    str
 2   Age          714 non-null    float64
 3   Fare         891 non-null    float64
dtypes: float64(2), int64(1), str(1)
memory usage: 32.1 KB

In [34]:
xls=pd.ExcelFile("titanic.xlsx")
print(xls.sheet_names)

['Sheet1']

In [35]:
df_sheet_name=pd.read_excel("titanic.xlsx",sheet_name="Sheet1")

In [36]:
df_sheet_name

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

<b>Load the parquet file

In [37]:
df_parquet=pd.read_parquet("titanic.parquet")
df_parquet.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [39]:
df_parquet_subset=pd.read_parquet("titanic.parquet",
                              columns=["PassengerId","Age","Sex","Fare"])

In [40]:
df_parquet_subset

     PassengerId   Age     Sex     Fare
0              1  22.0    male   7.2500
1              2  38.0  female  71.2833
2              3  26.0  female   7.9250
3              4  35.0  female  53.1000
4              5  35.0    male   8.0500
..           ...   ...     ...      ...
886          887  27.0    male  13.0000
887          888  19.0  female  30.0000
888          889   NaN  female  23.4500
889          890  26.0    male  30.0000
890          891  32.0    male   7.7500

[891 rows x 4 columns]

**4. Load the csv file with different separtatin

In [43]:
df_tab=pd.read_csv("titanic-tab.csv",sep="\t")

In [44]:
df_tab.shape

(891, 12)

**5. Compare the file size**

In [50]:
def file_size(path):
    size_bytes=os.path.getsize(path)
    size_kb=round(size_bytes/1024,2)
    size_mb=round(size_kb/1024,2)
    return size_kb,size_mb

for f in ["titanic.csv","titanic.xlsx","titanic.parquet","titanic-tab.csv"]:
    kb,mb=file_size(f)
    print(f"size in kb: {kb} and size in mb: {mb}")

size in kb: 58.89 and size in mb: 0.06
size in kb: 67.22 and size in mb: 0.07
size in kb: 40.43 and size in mb: 0.04
size in kb: 58.91 and size in mb: 0.06