***pandas basics ***

In [5]:
%pip install pandas
import pandas as pd

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in c:\users\kaush\desktop\summerbreak\machine learning\machinelearning\.venv-1\lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kaush\desktop\summerbreak\machine learning\machinelearning\.venv-1\lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kaush\desktop\summerbreak\machine learning\machinelearning\.venv-1\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\kaush\desktop\summerbreak\machine learning\machinelearning\.venv-1\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\kaush\desktop\summerbreak\machine learning\machinelearning\.venv-1\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [8]:
s=pd.Series([10,20,30,40,50,60],name="Marks")
print(s)
print(s.mean())

0    10
1    20
2    30
3    40
4    50
5    60
Name: Marks, dtype: int64
35.0

In [16]:
data={
    "Name":["kaushal","vivek","piyush","Sahil"],
    "Age":[21,23,21,23],
    "Score":[85,91,88,45]
}
print(type(data))
print(data)
data_frame=pd.DataFrame(data)

<class 'dict'>
{'Name': ['kaushal', 'vivek', 'piyush', 'Sahil'], 'Age': [21, 23, 21, 23], 'Score': [85, 91, 88, 45]}

In [14]:

print(type(data_frame))
print(data_frame)

<class 'pandas.DataFrame'>
      Name  Age  Score
0  kaushal   21     85
1    vivek   23     91
2   piyush   21     88
3    Sahil   23     45

***Creating dataFrame into Csv file**

In [29]:
data_frame.to_csv("data.csv",index=False)

**Read Data from Csv file**

In [21]:
diab_df=pd.read_csv("diabetes.csv")

In [22]:
diab_df.shape

(768, 9)

In [23]:
diab_df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='str')

In [24]:
diab_df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [25]:
diab_df.tail()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [31]:
df=pd.read_csv("data.csv")

In [32]:
df.shape

(4, 3)

In [33]:
df

      Name  Age  Score
0  kaushal   21     85
1    vivek   23     91
2   piyush   21     88
3    Sahil   23     45

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Age     4 non-null      int64
 2   Score   4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [ ]:
print(df["Name"])

0    kaushal
1      vivek
2     piyush
3      Sahil
Name: Name, dtype: str

In [36]:
print(df[["Name","Age"]])

      Name  Age
0  kaushal   21
1    vivek   23
2   piyush   21
3    Sahil   23

In [ ]:
print(df.iloc[0:2])

      Name  Age  Score
0  kaushal   21     85
1    vivek   23     91

<h1>Filtering the Data<h1/>

In [42]:
df

      Name  Age  Score
0  kaushal   21     85
1    vivek   23     91
2   piyush   21     88
3    Sahil   23     45

In [45]:
high_scores=df[df["Score"]>=85]
high_scores

      Name  Age  Score
0  kaushal   21     85
1    vivek   23     91
2   piyush   21     88

In [47]:
low_scores=df[df["Score"]<90]
low_scores

      Name  Age  Score
0  kaushal   21     85
2   piyush   21     88
3    Sahil   23     45

**Modification**

In [49]:
df["Passed"]=df["Score"]>80
print(df)

      Name  Age  Score  Passed
0  kaushal   21     85    True
1    vivek   23     91    True
2   piyush   21     88    True
3    Sahil   23     45   False

In [50]:
df["Percentage"]=df["Score"]/100 *100

In [51]:
df

      Name  Age  Score  Passed  Percentage
0  kaushal   21     85    True        85.0
1    vivek   23     91    True        91.0
2   piyush   21     88    True        88.0
3    Sahil   23     45   False        45.0

In [54]:
df["city"]=["NewYork","Mumbai","Delhi","Patna"]
df

      Name  Age  Score  Passed  Percentage     city
0  kaushal   21     85    True        85.0  NewYork
1    vivek   23     91    True        91.0   Mumbai
2   piyush   21     88    True        88.0    Delhi
3    Sahil   23     45   False        45.0    Patna

In [57]:
print("Average_Score:",df["Score"].mean())
print("Average_Score:",df["Score"].min())
print("Average_Score:",df["Score"].max())

Average_Score: 77.25
Average_Score: 45
Average_Score: 91

In [58]:
df.describe()

             Age      Score  Percentage
count   4.000000   4.000000    4.000000
mean   22.000000  77.250000   77.250000
std     1.154701  21.639085   21.639085
min    21.000000  45.000000   45.000000
25%    21.000000  75.000000   75.000000
50%    22.000000  86.500000   86.500000
75%    23.000000  88.750000   88.750000
max    23.000000  91.000000   91.000000

*Handling missing Data*